# AUTO-GENERATED from logistic_regression_hold_out.ipynb — do not edit.
# Regenerate: python ali_code/LLM_visualization/build_logistic_module.py
#!/usr/bin/env python
# coding: utf-8

# In[2]:


import numpy as np
import matplotlib.pyplot as plt
import math
import cvxpy as cp


# In[ ]:


class LogisticRegressionClass:

    def __init__(self, n, d, random_seed = 42, eta = 0.1):
        self.d = d
        self.n = n
        self.rng = np.random.default_rng(random_seed)
        self.eta = eta
    def ell(self, t):
        return np.logaddexp(0,-t)

    def zero_one_loss(self, w, X_data, y_data):
        n = len(X_data)
        predictions = np.sign(X_data @ w)
        return (1/n) * np.sum(predictions != y_data)

    def logistic_loss(self, w, X_data, y_data):
        n = len(X_data)
        return (1/n) * np.sum(self.ell( y_data * (X_data @ w)))

    def calibration_error(self):
        pass


    def oracular_ell_hat_w_star_zero_to_k(self, X_data, y_data,
                                          w_star,  Sigma=None, k=None,
                                          ):

        # Note: This function is not implemented for the general case! 
        # Right now, it just returns \hat{L}(w*) since w* = w*_{0:k} in our specific case
        return self.logistic_loss(w_star, X_data, y_data)

    def generate_data(self, d, n, w_star, Sigma = None, lambda_diag = None, use_lambda_diag=True):

        # LLM GENERATED PART ---------------------- 
        # generate X: sample N(0, I) then scale by sqrt(lambda)
        if use_lambda_diag:
            Z = self.rng.standard_normal((n, d))
            X_data = Z * np.sqrt(lambda_diag)  # broadcasts across rows
        else:
            X_data = self.rng.multivariate_normal(np.zeros(d), Sigma, size = n)
        # ------------------------------------------


        # generate y
        probs = 1.0/(1.0 + np.exp(- X_data @ w_star))
        random_draws = self.rng.uniform(low=0, high=1, size = n)
        y_data = - 1 + 2 * (random_draws <= probs).astype(float)

        return X_data, y_data

    def sigmoid(self, x):
        return np.where(x >= 0, 1/(1+np.exp(-x)), np.exp(x)/(1+np.exp(x)))

    def grad(self, w, X_data, y_data):
        n = len(X_data)
        return - (1/n) * X_data.T @ ((1-self.sigmoid(y_data * (X_data @ w)))*y_data)

    def record_the_error(n, mode = "all"):
        if mode == "all":
            return True
        if mode == "log": 
            return n > 0 and 10 ** round(math.log10(n)) == n # note: this line is generated by LLM and not carefully checked
        return False

    def run_GD_for_t_steps(self, X_data, y_data, X_valid=None, 
                           y_valid=None, X_test=None, y_test=None, 
                           w_0 = None, eta = None, t_steps = 10
                           , store_log_loss_traj_for_training = True
                           , store_log_loss_traj_for_validation = False
                           , store_log_loss_traj_for_test = False
                           , store_zero_one_loss_traj_for_training = True
                           , store_zero_one_loss_traj_for_validation = False
                           , store_zero_one_loss_traj_for_test = False
                           , store_w_trajectory = True):

        if w_0 is None:
            w_0 = np.zeros(self.d)#.reshape(-1,1)
        if eta is None:
            eta = self.eta

        logistic_loss_training_trajectory = []
        logistic_loss_validation_trajectory = []
        logistic_loss_test_trajectory = []

        zero_one_loss_training_trajectory = []
        zero_one_loss_validation_trajectory = []
        zero_one_loss_test_trajectory = []

        w_trajectory = []

        w_current = w_0

        # store w_0
        if store_w_trajectory:
            w_trajectory.append(w_current)

        for t in range(t_steps):
            # measure the error for w_prev

            # log loss ---------------------------------------
            if store_log_loss_traj_for_training:
                logistic_loss_training_trajectory.append(
                self.logistic_loss(
                    w_current, X_data, y_data
                    )
                )
            if store_log_loss_traj_for_validation:
                logistic_loss_validation_trajectory.append(
                self.logistic_loss(
                    w_current, X_valid, y_valid
                    )
                )
            if store_log_loss_traj_for_test:
                logistic_loss_test_trajectory.append(
                self.logistic_loss(
                    w_current, X_test, y_test
                    )
                )
            # zero-one loss --------------------------------------
            if store_zero_one_loss_traj_for_training:
                zero_one_loss_training_trajectory.append(
                    self.zero_one_loss(w_current, X_data, y_data)
                    )
            if store_zero_one_loss_traj_for_validation:
                zero_one_loss_validation_trajectory.append(
                    self.zero_one_loss(w_current, X_valid, y_valid)
                )
            if store_zero_one_loss_traj_for_test:
                zero_one_loss_test_trajectory.append(
                    self.zero_one_loss(w_current, X_test, y_test)
                )


            # gradient step
            w_new = w_current - eta * self.grad(w_current, X_data, y_data)
            w_current = w_new

            # store the w_t
            if store_w_trajectory:
                w_trajectory.append(w_current)

        return { 
            "log_loss_train": logistic_loss_training_trajectory,
            "log_loss_valid": logistic_loss_validation_trajectory,
            "log_loss_test": logistic_loss_test_trajectory,
            "zero_one_train": zero_one_loss_training_trajectory,
            "zero_one_valid": zero_one_loss_validation_trajectory,
            "zero_one_test": zero_one_loss_test_trajectory,
            "w_trajectory": w_trajectory,
            "w_last_iterate": w_current
        }


    def proj_on_2d_subspace(self, d_dimensional_vectors, v1, v2) :
        u1 = v1/np.linalg.norm(v1)
        v2_prep = v2 - np.dot(v2, u1) * u1
        u2 = v2_prep/np.linalg.norm(v2_prep)

        W = np.array(d_dimensional_vectors) 
        proj_1 = W @ u1
        proj_2 = W @ u2
        return np.stack([proj_1, proj_2], axis=-1)


    def plot_loss_over_time(self, logistic_loss_training_trajectory=None, zero_one_loss_training_trajectory=None,
         logistic_loss_validation_trajectory=None, zero_one_loss_validation_trajectory=None,
         logistic_loss_test_trajectory=None, zero_one_loss_test_trajectory=None, eta=None,
         bayes_logistic_risk=None, bayes_zero_one_risk=None,
         oracle_stop_opt_length=None,
         show_oracular_early_stopping=False, L_hat_of_w_start_zero_to_k=None,
         show_validation_arg_min=False
         ):

        if eta is None:
            eta = self.eta

        def make_opt_length(traj):
            return eta * np.arange(1, len(traj))

        # find oracle stopping point: first t where L_hat(w_t) <= L_hat(w*_{0:k})
        oracle_stop_opt_length = None
        if show_oracular_early_stopping and L_hat_of_w_start_zero_to_k is not None and logistic_loss_training_trajectory is not None:
            for t, loss in enumerate(logistic_loss_training_trajectory):
                if loss <= L_hat_of_w_start_zero_to_k:
                    oracle_stop_opt_length = eta * t
                    break

        # compute validation argmin stopping point from validation log loss trajectory
        valid_stop_opt_length = None
        if show_validation_arg_min and logistic_loss_validation_trajectory is not None and len(logistic_loss_validation_trajectory) > 1:
            argmin_idx = np.argmin(logistic_loss_validation_trajectory[1:])
            valid_stop_opt_length = eta * (argmin_idx + 1)

        fig, axes = plt.subplots(1, 2, figsize=(14, 6))

        if logistic_loss_training_trajectory is not None:
            opt_length = make_opt_length(logistic_loss_training_trajectory)
            axes[0].plot(opt_length, logistic_loss_training_trajectory[1:], label="training", color="tab:blue")
        if logistic_loss_validation_trajectory is not None:
            opt_length = make_opt_length(logistic_loss_validation_trajectory)
            axes[0].plot(opt_length, logistic_loss_validation_trajectory[1:], label="validation", color="tab:orange")
        if logistic_loss_test_trajectory is not None:
            opt_length = make_opt_length(logistic_loss_test_trajectory)
            axes[0].plot(opt_length, logistic_loss_test_trajectory[1:], label="test", color="tab:red")
        if bayes_logistic_risk is not None:
            axes[0].axhline(bayes_logistic_risk, linestyle=":", color="gray", label="bayes risk")
        if oracle_stop_opt_length is not None:
            axes[0].axvline(oracle_stop_opt_length, linestyle="--", color="green", label="oracle early stop")
        if valid_stop_opt_length is not None:
            axes[0].axvline(valid_stop_opt_length, linestyle="--", color="purple", label="valid early stop")
        axes[0].set_xscale("log")
        axes[0].set_yscale("log", base=2)
        axes[0].set_xlabel("opt length")
        axes[0].set_ylabel("logistic risk")
        axes[0].legend()

        if zero_one_loss_training_trajectory is not None:
            opt_length = make_opt_length(zero_one_loss_training_trajectory)
            axes[1].plot(opt_length, zero_one_loss_training_trajectory[1:], label="training", color="tab:blue")
        if zero_one_loss_validation_trajectory is not None:
            opt_length = make_opt_length(zero_one_loss_validation_trajectory)
            axes[1].plot(opt_length, zero_one_loss_validation_trajectory[1:], label="validation", color="tab:orange")
        if zero_one_loss_test_trajectory is not None:
            opt_length = make_opt_length(zero_one_loss_test_trajectory)
            axes[1].plot(opt_length, zero_one_loss_test_trajectory[1:], label="test", color="tab:red")
        if bayes_zero_one_risk is not None:
            axes[1].axhline(bayes_zero_one_risk, linestyle=":", color="gray", label="bayes risk")
        if oracle_stop_opt_length is not None:
            axes[1].axvline(oracle_stop_opt_length, linestyle="--", color="green", label="oracle early stop")
        if valid_stop_opt_length is not None:
            axes[1].axvline(valid_stop_opt_length, linestyle="--", color="purple", label="valid early stop")
        axes[1].set_xscale("log")
        axes[1].set_xlabel("opt length")
        axes[1].set_ylabel("zero-one error")
        axes[1].legend()

        plt.tight_layout()
        plt.show()

    def find_w_tilde(self, X_data, y_data, normalize=False): # Note: LLM generated
        n, d = X_data.shape
        Xy = X_data * y_data[:, None]                      # rows: y_i * x_i

        w = cp.Variable(d)
        objective = cp.Minimize(0.5 * cp.sum_squares(w))
        constraints = [Xy @ w >= 1]                        # y_i (x_i . w) >= 1
        prob = cp.Problem(objective, constraints)
        prob.solve()

        if prob.status not in ("optimal", "optimal_inaccurate"):
            raise RuntimeError(f"SVM QP not solved (status={prob.status}); "
                            "is the data linearly separable?")
        w_val = np.asarray(w.value).ravel()
        return w_val / np.linalg.norm(w_val) if normalize else w_val




    # def plot_trajectory_over(self, w_1, w_2, trajectory_dict_perhaps):
    #     pass

    def LLM_generated_region_experiment_v1(self, number_of_trajectories, w_star,
                                            d=None, n=None, t_steps=1000, eta=None,
                                            Sigma=None, lambda_diag=None, use_lambda_diag=True,
                                            normalize_w_tilde=False, plot=True):

        # LLM GENERATED PART ----------------------
        # Implements the plan sketched in region_experiment_v1:
        #   for each of `number_of_trajectories` runs, generate fresh data,
        #   run GD to get a trajectory, and find its max-margin w_tilde.
        # Then project every trajectory onto the 2D space spanned by
        #   w_1 = w_star (normalized) and w_2 = normalized sum of all w_tilde[i],
        # and plot the projected trajectories.
        # ------------------------------------------
        # Note: Ali looked at this code, seems fine, I didn't dig into the plot sections 
        # but anything before, it was fine. Confidence 80%
        # ------------------------------------------
        if d is None:
            d = self.d
        if n is None:
            n = self.n
        if eta is None:
            eta = self.eta

        trajectories = []
        w_tildes = []

        for i in range(number_of_trajectories):
            X_data, y_data = self.generate_data(
                d, n, w_star, Sigma=Sigma, lambda_diag=lambda_diag,
                use_lambda_diag=use_lambda_diag
            )

            result = self.run_GD_for_t_steps(
                X_data, y_data, eta=eta, t_steps=t_steps,
                store_w_trajectory=True
            )
            trajectory = result["w_trajectory"]

            w_tilde = self.find_w_tilde(X_data, y_data, normalize=normalize_w_tilde)

            trajectories.append(trajectory)
            w_tildes.append(w_tilde)

        # w_1 axis: direction of w_star
        w_star_norm = np.linalg.norm(w_star)
        w_1_direction = w_star / w_star_norm if w_star_norm > 0 else w_star

        # w_2 axis: direction of the sum of all w_tilde[i]
        w_tilde_sum = np.sum(w_tildes, axis=0)
        w_tilde_sum_norm = np.linalg.norm(w_tilde_sum)
        w_2_direction = w_tilde_sum / w_tilde_sum_norm if w_tilde_sum_norm > 0 else w_tilde_sum

        # project each trajectory onto (w_1_direction, w_2_direction)
        projected_trajectories = []


        # Since the trajectories have the same length, we do the projections in vectorized way 
        # instead of the one below 
        # --------------------------------------------
        # for trajectory in trajectories:
        # #     W = np.array(trajectory)  # shape (t_steps+1, d)
        # #     proj_1 = W @ w_1_direction
        # #     proj_2 = W @ w_2_direction
        #     projected_traj = self.proj_on_2d_subspace(trajectory, w_1_direction, w_2_direction)
        #     projected_trajectories.append(projected_traj)
        # --------------------------------------------
        # -----
        # Vectorized Version below
        # -----
        # --------------------------------------------
        projected_trajectories = self.proj_on_2d_subspace(trajectories, w_1_direction, w_2_direction)
        # --------------------------------------------

        if plot:
            plt.figure(figsize=(7, 7))
            for idx, proj in enumerate(projected_trajectories):
                plt.plot(proj[:, 0], proj[:, 1], marker="o", markersize=2,
                         label=f"trajectory {idx}")
                plt.scatter(proj[0, 0], proj[0, 1], color="black", zorder=5)  # start
                plt.scatter(proj[-1, 0], proj[-1, 1], color="red", zorder=5)  # end
            plt.xlabel("w_1 = w* direction")
            plt.ylabel("w_2 = sum(w_tilde) direction")
            plt.title("GD trajectories projected onto (w*, sum w_tilde) plane")
            plt.legend()
            plt.tight_layout()
            plt.show()

        return {
            "trajectories": trajectories,
            "w_tildes": w_tildes,
            "w_1_direction": w_1_direction,
            "w_2_direction": w_2_direction,
            "projected_trajectories": projected_trajectories,
        }
        # ------------------------------------------


        # ------------------------------------------



    def LLM_generated_region_experiment_v2(self, number_of_trajectories, w_star,
                                            d=None, n=None, t_steps=1000, eta=None,
                                            Sigma=None, lambda_diag=None, use_lambda_diag=True,
                                            normalize_w_tilde=False, plot=True,
                                            test_sample_size=int(3e3),
                                            measure_population_loss_for_iterates=True,
                                            ):
        # Similar to V1, except we also generate a shared test set (if
        # measure_population_loss_for_iterates=True) to approximate the population loss.
        # Per trajectory we record two stopping points (both indices into w_trajectory,
        # since loss[t] corresponds to w_trajectory[t]):
        #   - early_stop_t:        first t with TRAINING loss <= L_hat(w*_{0:k})
        #                          (the oracular early-stopping rule; training-based).
        #   - test_loss_argmin_t:  argmin_t of the population (test) logistic loss
        #                          -> the "best" iterate to stop at.
        if d is None:
            d = self.d
        if n is None:
            n = self.n
        if eta is None:
            eta = self.eta

        # single shared test set approximating the population (same distribution for
        # every trajectory, so one test set suffices).
        X_test = y_test = None
        if measure_population_loss_for_iterates:
            X_test, y_test = self.generate_data(
                d, int(test_sample_size), w_star, Sigma=Sigma,
                lambda_diag=lambda_diag, use_lambda_diag=use_lambda_diag
            )

        trajectories = []
        w_tildes = []
        early_stop_t = []        # per trajectory: t of training-based oracular early stop
        test_loss_argmin_t = []  # per trajectory: t of argmin population (test) loss

        for i in range(number_of_trajectories):
            X_data, y_data = self.generate_data(
                d, n, w_star, Sigma=Sigma, lambda_diag=lambda_diag,
                use_lambda_diag=use_lambda_diag
            )

            result = self.run_GD_for_t_steps(
                X_data, y_data, eta=eta, t_steps=t_steps,
                X_test=X_test, y_test=y_test,
                store_w_trajectory=True,
                store_log_loss_traj_for_training=True,
                store_log_loss_traj_for_test=measure_population_loss_for_iterates,
            )
            trajectory = result["w_trajectory"]

            w_tilde = self.find_w_tilde(X_data, y_data, normalize=normalize_w_tilde)

            trajectories.append(trajectory)
            w_tildes.append(w_tilde)

            train_log_loss = result["log_loss_train"]
            test_log_loss = result["log_loss_test"]

            # early-stopping point: first t with L_train(w_t) <= L_train(w*_{0:k}).
            # Both the threshold and the loss trajectory use the TRAINING data.
            L_hat_w_star = self.oracular_ell_hat_w_star_zero_to_k(X_data, y_data, w_star)
            es_t = None
            for t, loss in enumerate(train_log_loss):
                if loss <= L_hat_w_star:
                    es_t = t
                    break
            early_stop_t.append(es_t)

            # argmin of the population (test) logistic loss
            am_t = None
            if measure_population_loss_for_iterates and len(test_log_loss) > 0:
                am_t = int(np.argmin(test_log_loss))
            test_loss_argmin_t.append(am_t)

        # w_1 axis: direction of w_star
        w_star_norm = np.linalg.norm(w_star)
        w_1_direction = w_star / w_star_norm if w_star_norm > 0 else w_star

        # w_2 axis: direction of the sum of all w_tilde[i]
        w_tilde_sum = np.sum(w_tildes, axis=0)
        w_tilde_sum_norm = np.linalg.norm(w_tilde_sum)
        w_2_direction = w_tilde_sum / w_tilde_sum_norm if w_tilde_sum_norm > 0 else w_tilde_sum

        # project each trajectory onto (w_1_direction, w_2_direction)
        # Since the trajectories have the same length, we do the projections in vectorized way 
        # instead of the one below 
        # --------------------------------------------
        # for trajectory in trajectories:
        # #     W = np.array(trajectory)  # shape (t_steps+1, d)
        # #     proj_1 = W @ w_1_direction
        # #     proj_2 = W @ w_2_direction
        #     projected_traj = self.proj_on_2d_subspace(trajectory, w_1_direction, w_2_direction)
        #     projected_trajectories.append(projected_traj)
        # --------------------------------------------
        # -----
        # Vectorized Version below
        # -----
        # --------------------------------------------
        projected_trajectories = self.proj_on_2d_subspace(trajectories, w_1_direction, w_2_direction)
        # --------------------------------------------

        if plot:
            plt.figure(figsize=(7, 7))
            for idx, proj in enumerate(projected_trajectories):
                plt.plot(proj[:, 0], proj[:, 1], marker="o", markersize=2,
                         label=f"trajectory {idx}")
                plt.scatter(proj[0, 0], proj[0, 1], color="black", zorder=5)  # start
                plt.scatter(proj[-1, 0], proj[-1, 1], color="red", zorder=5)  # end
                es = early_stop_t[idx]
                am = test_loss_argmin_t[idx]
                if es is not None:
                    plt.scatter(proj[es, 0], proj[es, 1], color="green",
                                marker="s", zorder=6,
                                label="early stop" if idx == 0 else None)
                if am is not None:
                    plt.scatter(proj[am, 0], proj[am, 1], color="purple",
                                marker="*", s=120, zorder=6,
                                label="test-loss argmin" if idx == 0 else None)
            plt.xlabel("w_1 = w* direction")
            plt.ylabel("w_2 = sum(w_tilde) direction")
            plt.title("GD trajectories projected onto (w*, sum w_tilde) plane")
            plt.legend()
            plt.tight_layout()
            plt.show()

        return {
            "trajectories": trajectories,
            "w_tildes": w_tildes,
            "w_1_direction": w_1_direction,
            "w_2_direction": w_2_direction,
            "projected_trajectories": projected_trajectories,
            "early_stop_t": early_stop_t,
            "test_loss_argmin_t": test_loss_argmin_t,
        }


    def LLM_generated_region_experiment_v3(self, number_of_trajectories, w_star,
                                        d=None, n=None, t_steps=1000, eta=None,
                                        Sigma=None, lambda_diag=None, use_lambda_diag=True,
                                        normalize_w_tilde=False, plot=True,
                                        test_sample_size=int(3e3),
                                        measure_population_loss_for_iterates=True,
                                        n_random_axes=2   # how many isotropic random axes to add to the stored set
                                        ):
    # Similar to V1, except we also generate a shared test set (if
    # measure_population_loss_for_iterates=True) to approximate the population loss.
    # Per trajectory we record two stopping points (both indices into w_trajectory,
    # since loss[t] corresponds to w_trajectory[t]):
    #   - early_stop_t:        first t with TRAINING loss <= L_hat(w*_{0:k})
    #                          (the oracular early-stopping rule; training-based).
    #   - test_loss_argmin_t:  argmin_t of the population (test) logistic loss
    #                          -> the "best" iterate to stop at.
    #
    # NEW in V3: instead of committing to a single fixed projection plane, we store
    # the raw dot products of every iterate against a whole SET of candidate axes
    #   v = [w*, w~_0, ..., w~_{m-1}, sum_w~, rand_0, ..., rand_{r-1}]   (all unit-norm)
    # namely P[i, t, a] = <w_{i,t}, v_a>, plus the axis Gram matrix G[a, b] = <v_a, v_b>.
    # The visualization can then pick ANY pair of axes (a, b) and reconstruct the exact
    # orthonormal 2D projection at view time (no re-running GD, no storing d-dim data):
    #     x_t = P[i, t, a] / sqrt(G[a, a])
    #     y_t = (P[i, t, b] - (G[a, b]/G[a, a]) * P[i, t, a])
    #           / sqrt(G[b, b] - G[a, b]**2 / G[a, a])
    # (with unit-norm axes G[a, a] = 1, so x_t = P[i, t, a]). Because w* and each w~_i are
    # themselves axes, their marker positions come for free from the same P/G.
        if d is None:
            d = self.d
        if n is None:
            n = self.n
        if eta is None:
            eta = self.eta


        # single shared test set approximating the population (same distribution for
        # every trajectory, so one test set suffices).
        X_test = y_test = None
        if measure_population_loss_for_iterates:
            X_test, y_test = self.generate_data(
                d, int(test_sample_size), w_star, Sigma=Sigma,
                lambda_diag=lambda_diag, use_lambda_diag=use_lambda_diag
            )

        trajectories = []
        w_tildes = []
        early_stop_t = []        # per trajectory: t of training-based oracular early stop
        test_loss_argmin_t = []  # per trajectory: t of argmin population (test) loss

        for i in range(number_of_trajectories):
            X_data, y_data = self.generate_data(
                d, n, w_star, Sigma=Sigma, lambda_diag=lambda_diag,
                use_lambda_diag=use_lambda_diag
            )

            result = self.run_GD_for_t_steps(
                X_data, y_data, eta=eta, t_steps=t_steps,
                X_test=X_test, y_test=y_test,
                store_w_trajectory=True,
                store_log_loss_traj_for_training=True,
                store_log_loss_traj_for_test=measure_population_loss_for_iterates,
            )
            trajectory = result["w_trajectory"]

            w_tilde = self.find_w_tilde(X_data, y_data, normalize=normalize_w_tilde)

            trajectories.append(trajectory)
            w_tildes.append(w_tilde)

            train_log_loss = result["log_loss_train"]
            test_log_loss = result["log_loss_test"]

            # early-stopping point: first t with L_train(w_t) <= L_train(w*_{0:k}).
            # Both the threshold and the loss trajectory use the TRAINING data.
            L_hat_w_star = self.oracular_ell_hat_w_star_zero_to_k(X_data, y_data, w_star)
            es_t = None
            for t, loss in enumerate(train_log_loss):
                if loss <= L_hat_w_star:
                    es_t = t
                    break
            early_stop_t.append(es_t)

            # argmin of the population (test) logistic loss
            am_t = None
            if measure_population_loss_for_iterates and len(test_log_loss) > 0:
                am_t = int(np.argmin(test_log_loss))
            test_loss_argmin_t.append(am_t)

        # sum of the per-trajectory max-margin directions (a stored candidate axis, and the
        # default y-axis for the in-function plot).
        sum_w_tilde = np.sum(np.asarray(w_tildes, dtype=float), axis=0)

        # ---- candidate projection axes (all unit-normalized so the comparison is fair) ----
        # Several axes are derived from the run itself (one w~_i per trajectory and their
        # sum), so they are assembled here rather than passed in. The random axes are drawn
        # from the instance RNG (self.rng), so the axis set is reproducible for a given seed.
        def _unit_rows(M):
            M = np.asarray(M, dtype=float)
            return M / np.linalg.norm(M, axis=-1, keepdims=True)

        axis_vectors = [np.asarray(w_star, dtype=float)]
        axis_labels = ["w*"]
        for i in range(number_of_trajectories):
            axis_vectors.append(np.asarray(w_tildes[i], dtype=float))
            axis_labels.append(f"w~_{i}")
        axis_vectors.append(sum_w_tilde)
        axis_labels.append("sum_w~")
        for j in range(n_random_axes):
            axis_vectors.append(self.rng.standard_normal(d))
            axis_labels.append(f"rand_{j}")

        A = _unit_rows(np.array(axis_vectors))     # (n_axes, d), unit-norm rows
        W = np.array(trajectories)                 # (n_traj, T, d)
        P = W @ A.T                                # (n_traj, T, n_axes): <w_{i,t}, v_a>
        G = A @ A.T                                # (n_axes, n_axes): <v_a, v_b>

        # default 2D view for the in-function plot: project onto the (w*, sum_w~) plane.
        # The visualization is free to reconstruct any other axis pair from P / G at view
        # time; this is just a convenience preview. proj_on_2d_subspace orthonormalizes the
        # pair internally (Gram-Schmidt), matching the view-time reconstruction above.
        projected_trajectories = self.proj_on_2d_subspace(trajectories, w_star, sum_w_tilde)

        if plot:
            plt.figure(figsize=(7, 7))
            for idx, proj in enumerate(projected_trajectories):
                plt.plot(proj[:, 0], proj[:, 1], marker="o", markersize=2,
                            label=f"trajectory {idx}")
                plt.scatter(proj[0, 0], proj[0, 1], color="black", zorder=5)  # start
                plt.scatter(proj[-1, 0], proj[-1, 1], color="red", zorder=5)  # end
                es = early_stop_t[idx]
                am = test_loss_argmin_t[idx]
                if es is not None:
                    plt.scatter(proj[es, 0], proj[es, 1], color="green",
                                marker="s", zorder=6,
                                label="early stop" if idx == 0 else None)
                if am is not None:
                    plt.scatter(proj[am, 0], proj[am, 1], color="purple",
                                marker="*", s=120, zorder=6,
                                label="test-loss argmin" if idx == 0 else None)
            plt.xlabel("w* direction")
            plt.ylabel("sum(w_tilde) direction")
            plt.title("GD trajectories projected onto (w*, sum w_tilde) plane")
            plt.legend()
            plt.tight_layout()
            plt.show()

        # We deliberately do NOT return the full d-dim `trajectories` (huge). Everything the
        # visualization needs to redraw any projection is in P / G / axis_labels; the two
        # stopping points are indices into the time axis of P.
        return {
            "P": P,                          # (n_traj, T, n_axes): <w_{i,t}, v_a>
            "G": G,                          # (n_axes, n_axes): axis Gram matrix
            "axis_labels": axis_labels,      # names aligned with the axis dimension of P and G
            "w_star": np.asarray(w_star, dtype=float),   # raw reference vectors at TRUE magnitude,
            "w_tildes": w_tildes,                        # returned independently for the viz to project
            "early_stop_t": early_stop_t,
            "test_loss_argmin_t": test_loss_argmin_t,
        }
    def LLM_generated_trajectory_comparison_over_time(self, w_star,
                                    d=None, n=None, t_steps=1000, eta=None,
                                    Sigma=None, lambda_diag=None, use_lambda_diag=True,
                                    k_list=(5, 10, 15, 50),
                                    test_sample_size=int(3e3),
                                    measure_population_loss_for_iterates=True,
                                    plot=True):
    # A NEW plot type (NOT a spatial projection like v1/v2/v3): the x-axis is TIME
    # (the GD step t). We run exactly TWO GD trajectories from two INDEPENDENT data
    # draws of the same distribution (same w*), then compare them over time:
    #
    #   1. angle(w1_t, w2_t)      -- angle (radians) between the two full weight
    #                               vectors at each step. Single (T,) series.
    #   2. ||w1_t - w2_t||        -- L2 norm of their difference, restricted to a
    #                               COORDINATE SUBSET. For every k in k_list we store
    #                               both the FIRST-k coords and the LAST (d-k) coords,
    #                               and (once) the norm over ALL d coords.
    #
    # These metrics need the actual weight vectors over time, so unlike v3 this does
    # NOT use the P/G projection machinery -- it works on the full w_t directly.
    #
    # Shapes: run_GD_for_t_steps stores w_0 (=zeros) then t_steps updates, so each
    # trajectory has T = t_steps + 1 iterates. The loss trajectories have length
    # t_steps, and loss[t] corresponds to w_trajectory[t]; the stop indices below are
    # therefore valid indices into the (T,) metric arrays. angle at t=0 is undefined
    # (both trajectories are the zero vector) and is set to NaN.
        if d is None:
            d = self.d
        if n is None:
            n = self.n
        if eta is None:
            eta = self.eta

        # single shared test set approximating the population (same distribution for
        # both trajectories, so one test set suffices).
        X_test = y_test = None
        if measure_population_loss_for_iterates:
            X_test, y_test = self.generate_data(
                d, int(test_sample_size), w_star, Sigma=Sigma,
                lambda_diag=lambda_diag, use_lambda_diag=use_lambda_diag
            )

        trajectories = []
        early_stop_t = []        # per trajectory: t of training-based oracular early stop
        test_loss_argmin_t = []  # per trajectory: t of argmin population (test) loss

        for i in range(2):
            X_data, y_data = self.generate_data(
                d, n, w_star, Sigma=Sigma, lambda_diag=lambda_diag,
                use_lambda_diag=use_lambda_diag
            )

            result = self.run_GD_for_t_steps(
                X_data, y_data, eta=eta, t_steps=t_steps,
                X_test=X_test, y_test=y_test,
                store_w_trajectory=True,
                store_log_loss_traj_for_training=True,
                store_log_loss_traj_for_test=measure_population_loss_for_iterates,
            )
            trajectories.append(np.asarray(result["w_trajectory"], dtype=float))  # (T, d)

            train_log_loss = result["log_loss_train"]
            test_log_loss = result["log_loss_test"]

            # early-stopping point: first t with L_train(w_t) <= L_train(w*_{0:k}).
            L_hat_w_star = self.oracular_ell_hat_w_star_zero_to_k(X_data, y_data, w_star)
            es_t = None
            for t, loss in enumerate(train_log_loss):
                if loss <= L_hat_w_star:
                    es_t = t
                    break
            early_stop_t.append(es_t)

            # argmin of the population (test) logistic loss
            am_t = None
            if measure_population_loss_for_iterates and len(test_log_loss) > 0:
                am_t = int(np.argmin(test_log_loss))
            test_loss_argmin_t.append(am_t)

        W1, W2 = trajectories[0], trajectories[1]   # each (T, d)
        T = W1.shape[0]

        # ---- angle(w1_t, w2_t) over time (full vectors, radians) ----
        dot = np.sum(W1 * W2, axis=1)               # (T,)
        norm1 = np.linalg.norm(W1, axis=1)          # (T,)
        norm2 = np.linalg.norm(W2, axis=1)          # (T,)
        denom = norm1 * norm2
        with np.errstate(divide="ignore", invalid="ignore"):
            cos = np.where(denom > 0, dot / denom, np.nan)
        cos = np.clip(cos, -1.0, 1.0)
        angle = np.arccos(cos)                       # (T,), NaN where a vector is 0

        # ---- ||w1_t - w2_t|| over time, on coordinate subsets ----
        diff = W1 - W2                               # (T, d)
        diff_all = np.linalg.norm(diff, axis=1)     # (T,), over ALL d coords

        # per-k: first-k coords and last-(d-k) coords. k is clamped to [0, d].
        diff_first_k = {}   # k -> (T,) norm over coords [0:k]
        diff_last_k = {}    # k -> (T,) norm over coords [k:d]  (i.e. last d-k coords)
        k_list = [int(k) for k in k_list]
        for k in k_list:
            kk = max(0, min(k, d))
            diff_first_k[k] = np.linalg.norm(diff[:, :kk], axis=1)
            diff_last_k[k] = np.linalg.norm(diff[:, kk:], axis=1)

        if plot:
            n_rows = 2
            fig, axes = plt.subplots(n_rows, 1, figsize=(9, 8), sharex=True)
            ts = np.arange(T)

            # (1) angle over time
            ax0 = axes[0]
            ax0.plot(ts, angle, color="black", lw=1.5)
            ax0.set_ylabel("angle(w1_t, w2_t) [rad]")
            ax0.set_title("Angle between the two GD trajectories over time")

            # (2) norm-diff over time, all / per-k first / per-k last
            ax1 = axes[1]
            ax1.plot(ts, diff_all, color="black", lw=2, label="all d coords")
            for k in k_list:
                ax1.plot(ts, diff_first_k[k], lw=1, label=f"first {k}")
                ax1.plot(ts, diff_last_k[k], lw=1, ls="--", label=f"last d-{k}")
            ax1.set_ylabel("||w1_t - w2_t||")
            ax1.set_xlabel("GD step t")
            ax1.set_title("Norm of trajectory difference over time (coordinate subsets)")
            ax1.legend(fontsize=8, ncol=2)

            # early-stop (green dashed) and test-loss argmin (purple dotted) verticals
            for idx in range(2):
                es = early_stop_t[idx]
                am = test_loss_argmin_t[idx]
                if es is not None:
                    for ax in axes:
                        ax.axvline(es, color="green", ls="--", alpha=0.6,
                                    label=("early stop" if (idx == 0 and ax is ax0) else None))
                if am is not None:
                    for ax in axes:
                        ax.axvline(am, color="purple", ls=":", alpha=0.6,
                                    label=("test-loss argmin" if (idx == 0 and ax is ax0) else None))
            ax0.legend(fontsize=8)
            plt.tight_layout()
            plt.show()

        return {
            "angle": angle,                       # (T,), radians; NaN at t=0
            "diff_all": diff_all,                 # (T,), ||w1-w2|| over all d coords
            "diff_first_k": diff_first_k,         # dict: k -> (T,) over coords [0:k]
            "diff_last_k": diff_last_k,           # dict: k -> (T,) over coords [k:d]
            "k_list": k_list,
            "d": d,
            "early_stop_t": early_stop_t,         # [t1, t2] indices (or None)
            "test_loss_argmin_t": test_loss_argmin_t,  # [t1, t2] indices (or None)
        }



