# AUTO-GENERATED from logistic_regression_hold_out.ipynb — do not edit.
# Regenerate: python ali_code/LLM_visualization/build_logistic_module.py
#!/usr/bin/env python
# coding: utf-8

# In[3]:


import numpy as np
import matplotlib.pyplot as plt
import math
import cvxpy as cp


# In[ ]:


class LogisticRegressionClass:

    def __init__(self, n, d, random_seed = 42, eta = 0.1):
        self.d = d
        self.n = n
        self.rng = np.random.default_rng(random_seed)
        self.eta = eta
    def ell(self, t):
        return np.logaddexp(0,-t)

    def zero_one_loss(self, w, X_data, y_data):
        n = len(X_data)
        predictions = np.sign(X_data @ w)
        return (1/n) * np.sum(predictions != y_data)

    def logistic_loss(self, w, X_data, y_data):
        n = len(X_data)
        return (1/n) * np.sum(self.ell( y_data * (X_data @ w)))

    def calibration_error(self):
        pass


    def oracular_ell_hat_w_star_zero_to_k(self, X_data, y_data,
                                          w_star,  Sigma=None, k=None,
                                          ):

        # Note: This function is not implemented for the general case! 
        # Right now, it just returns \hat{L}(w*) since w* = w*_{0:k} in our specific case
        return self.logistic_loss(w_star, X_data, y_data)

    def generate_data(self, d, n, w_star, Sigma = None, lambda_diag = None, use_lambda_diag=True):

        # LLM GENERATED PART ---------------------- 
        # generate X: sample N(0, I) then scale by sqrt(lambda)
        if use_lambda_diag:
            Z = self.rng.standard_normal((n, d))
            X_data = Z * np.sqrt(lambda_diag)  # broadcasts across rows
        else:
            X_data = self.rng.multivariate_normal(np.zeros(d), Sigma, size = n)
        # ------------------------------------------


        # generate y
        probs = 1.0/(1.0 + np.exp(- X_data @ w_star))
        random_draws = self.rng.uniform(low=0, high=1, size = n)
        y_data = - 1 + 2 * (random_draws <= probs).astype(float)

        return X_data, y_data

    def sigmoid(self, x):
        return np.where(x >= 0, 1/(1+np.exp(-x)), np.exp(x)/(1+np.exp(x)))

    def grad(self, w, X_data, y_data):
        n = len(X_data)
        return - (1/n) * X_data.T @ ((1-self.sigmoid(y_data * (X_data @ w)))*y_data)

    def record_the_error(n, mode = "all"):
        if mode == "all":
            return True
        if mode == "log": 
            return n > 0 and 10 ** round(math.log10(n)) == n # note: this line is generated by LLM and not carefully checked
        return False

    def run_GD_for_t_steps(self, X_data, y_data, X_valid=None, 
                           y_valid=None, X_test=None, y_test=None, 
                           w_0 = None, eta = None, t_steps = 10
                           , store_log_loss_traj_for_training = True
                           , store_log_loss_traj_for_validation = False
                           , store_log_loss_traj_for_test = False
                           , store_zero_one_loss_traj_for_training = True
                           , store_zero_one_loss_traj_for_validation = False
                           , store_zero_one_loss_traj_for_test = False
                           , store_w_trajectory = True):

        if w_0 is None:
            w_0 = np.zeros(self.d)#.reshape(-1,1)
        if eta is None:
            eta = self.eta

        logistic_loss_training_trajectory = []
        logistic_loss_validation_trajectory = []
        logistic_loss_test_trajectory = []

        zero_one_loss_training_trajectory = []
        zero_one_loss_validation_trajectory = []
        zero_one_loss_test_trajectory = []

        w_trajectory = []

        w_current = w_0

        # store w_0
        if store_w_trajectory:
            w_trajectory.append(w_current)

        for t in range(t_steps):
            # measure the error for w_prev

            # log loss ---------------------------------------
            if store_log_loss_traj_for_training:
                logistic_loss_training_trajectory.append(
                self.logistic_loss(
                    w_current, X_data, y_data
                    )
                )
            if store_log_loss_traj_for_validation:
                logistic_loss_validation_trajectory.append(
                self.logistic_loss(
                    w_current, X_valid, y_valid
                    )
                )
            if store_log_loss_traj_for_test:
                logistic_loss_test_trajectory.append(
                self.logistic_loss(
                    w_current, X_test, y_test
                    )
                )
            # zero-one loss --------------------------------------
            if store_zero_one_loss_traj_for_training:
                zero_one_loss_training_trajectory.append(
                    self.zero_one_loss(w_current, X_data, y_data)
                    )
            if store_zero_one_loss_traj_for_validation:
                zero_one_loss_validation_trajectory.append(
                    self.zero_one_loss(w_current, X_valid, y_valid)
                )
            if store_zero_one_loss_traj_for_test:
                zero_one_loss_test_trajectory.append(
                    self.zero_one_loss(w_current, X_test, y_test)
                )


            # gradient step
            w_new = w_current - eta * self.grad(w_current, X_data, y_data)
            w_current = w_new

            # store the w_t
            if store_w_trajectory:
                w_trajectory.append(w_current)

        return { 
            "log_loss_train": logistic_loss_training_trajectory,
            "log_loss_valid": logistic_loss_validation_trajectory,
            "log_loss_test": logistic_loss_test_trajectory,
            "zero_one_train": zero_one_loss_training_trajectory,
            "zero_one_valid": zero_one_loss_validation_trajectory,
            "zero_one_test": zero_one_loss_test_trajectory,
            "w_trajectory": w_trajectory,
            "w_last_iterate": w_current
        }


    def plot_loss_over_time(self, logistic_loss_training_trajectory=None, zero_one_loss_training_trajectory=None,
         logistic_loss_validation_trajectory=None, zero_one_loss_validation_trajectory=None,
         logistic_loss_test_trajectory=None, zero_one_loss_test_trajectory=None, eta=None,
         bayes_logistic_risk=None, bayes_zero_one_risk=None,
         oracle_stop_opt_length=None,
         show_oracular_early_stopping=False, L_hat_of_w_start_zero_to_k=None,
         show_validation_arg_min=False
         ):

        if eta is None:
            eta = self.eta

        def make_opt_length(traj):
            return eta * np.arange(1, len(traj))

        # find oracle stopping point: first t where L_hat(w_t) <= L_hat(w*_{0:k})
        oracle_stop_opt_length = None
        if show_oracular_early_stopping and L_hat_of_w_start_zero_to_k is not None and logistic_loss_validation_trajectory is not None:
            for t, loss in enumerate(logistic_loss_validation_trajectory):
                if loss <= L_hat_of_w_start_zero_to_k:
                    oracle_stop_opt_length = eta * t
                    break

        # compute validation argmin stopping point from validation log loss trajectory
        valid_stop_opt_length = None
        if show_validation_arg_min and logistic_loss_validation_trajectory is not None and len(logistic_loss_validation_trajectory) > 1:
            argmin_idx = np.argmin(logistic_loss_validation_trajectory[1:])
            valid_stop_opt_length = eta * (argmin_idx + 1)

        fig, axes = plt.subplots(1, 2, figsize=(14, 6))

        if logistic_loss_training_trajectory is not None:
            opt_length = make_opt_length(logistic_loss_training_trajectory)
            axes[0].plot(opt_length, logistic_loss_training_trajectory[1:], label="training", color="tab:blue")
        if logistic_loss_validation_trajectory is not None:
            opt_length = make_opt_length(logistic_loss_validation_trajectory)
            axes[0].plot(opt_length, logistic_loss_validation_trajectory[1:], label="validation", color="tab:orange")
        if logistic_loss_test_trajectory is not None:
            opt_length = make_opt_length(logistic_loss_test_trajectory)
            axes[0].plot(opt_length, logistic_loss_test_trajectory[1:], label="test", color="tab:red")
        if bayes_logistic_risk is not None:
            axes[0].axhline(bayes_logistic_risk, linestyle=":", color="gray", label="bayes risk")
        if oracle_stop_opt_length is not None:
            axes[0].axvline(oracle_stop_opt_length, linestyle="--", color="green", label="oracle early stop")
        if valid_stop_opt_length is not None:
            axes[0].axvline(valid_stop_opt_length, linestyle="--", color="purple", label="valid early stop")
        axes[0].set_xscale("log")
        axes[0].set_yscale("log", base=2)
        axes[0].set_xlabel("opt length")
        axes[0].set_ylabel("logistic risk")
        axes[0].legend()

        if zero_one_loss_training_trajectory is not None:
            opt_length = make_opt_length(zero_one_loss_training_trajectory)
            axes[1].plot(opt_length, zero_one_loss_training_trajectory[1:], label="training", color="tab:blue")
        if zero_one_loss_validation_trajectory is not None:
            opt_length = make_opt_length(zero_one_loss_validation_trajectory)
            axes[1].plot(opt_length, zero_one_loss_validation_trajectory[1:], label="validation", color="tab:orange")
        if zero_one_loss_test_trajectory is not None:
            opt_length = make_opt_length(zero_one_loss_test_trajectory)
            axes[1].plot(opt_length, zero_one_loss_test_trajectory[1:], label="test", color="tab:red")
        if bayes_zero_one_risk is not None:
            axes[1].axhline(bayes_zero_one_risk, linestyle=":", color="gray", label="bayes risk")
        if oracle_stop_opt_length is not None:
            axes[1].axvline(oracle_stop_opt_length, linestyle="--", color="green", label="oracle early stop")
        if valid_stop_opt_length is not None:
            axes[1].axvline(valid_stop_opt_length, linestyle="--", color="purple", label="valid early stop")
        axes[1].set_xscale("log")
        axes[1].set_xlabel("opt length")
        axes[1].set_ylabel("zero-one error")
        axes[1].legend()

        plt.tight_layout()
        plt.show()

    def find_w_tilde(self, X_data, y_data, normalize=False): # Note: LLM generated
        n, d = X_data.shape
        Xy = X_data * y_data[:, None]                      # rows: y_i * x_i

        w = cp.Variable(d)
        objective = cp.Minimize(0.5 * cp.sum_squares(w))
        constraints = [Xy @ w >= 1]                        # y_i (x_i . w) >= 1
        prob = cp.Problem(objective, constraints)
        prob.solve()

        if prob.status not in ("optimal", "optimal_inaccurate"):
            raise RuntimeError(f"SVM QP not solved (status={prob.status}); "
                            "is the data linearly separable?")
        w_val = np.asarray(w.value).ravel()
        return w_val / np.linalg.norm(w_val) if normalize else w_val



    def region_experiment_v1(self,number_of_trajectories):

        # trajectories = []

        # generate data for k = number of trajectories
        # for i in range (0, k)
        # run GD for each one
        # # 1) Store the trajectory
        # # 2) find w_tilde
        # trajectories[i] = trajectory
        # w_tilde[i] = w_tilde
        # then plot all trajectories in space of 
        # w_1 = w^*
        # w_2 = sum of all w_tilde[i]
        # see how it looks
        # I'm testinggg11
        # 1
        pass

    def plot_trajectory_over(self, w_1, w_2, trajectory_dict_perhaps):
        pass

    def LLM_generated_region_experiment_v1(self, number_of_trajectories, w_star,
                                            d=None, n=None, t_steps=1000, eta=None,
                                            Sigma=None, lambda_diag=None, use_lambda_diag=True,
                                            normalize_w_tilde=False, plot=True):

        # LLM GENERATED PART ----------------------
        # Implements the plan sketched in region_experiment_v1:
        #   for each of `number_of_trajectories` runs, generate fresh data,
        #   run GD to get a trajectory, and find its max-margin w_tilde.
        # Then project every trajectory onto the 2D space spanned by
        #   w_1 = w_star (normalized) and w_2 = normalized sum of all w_tilde[i],
        # and plot the projected trajectories.
        # ------------------------------------------
        # Note: Ali looked at this code, seems fine, I didn't dig into the plot sections 
        # but anything before, it was fine. Confidence 80%
        # ------------------------------------------
        if d is None:
            d = self.d
        if n is None:
            n = self.n
        if eta is None:
            eta = self.eta

        trajectories = []
        w_tildes = []

        for i in range(number_of_trajectories):
            X_data, y_data = self.generate_data(
                d, n, w_star, Sigma=Sigma, lambda_diag=lambda_diag,
                use_lambda_diag=use_lambda_diag
            )

            result = self.run_GD_for_t_steps(
                X_data, y_data, eta=eta, t_steps=t_steps,
                store_w_trajectory=True
            )
            trajectory = result["w_trajectory"]

            w_tilde = self.find_w_tilde(X_data, y_data, normalize=normalize_w_tilde)

            trajectories.append(trajectory)
            w_tildes.append(w_tilde)

        # w_1 axis: direction of w_star
        w_star_norm = np.linalg.norm(w_star)
        w_1_direction = w_star / w_star_norm if w_star_norm > 0 else w_star

        # w_2 axis: direction of the sum of all w_tilde[i]
        w_tilde_sum = np.sum(w_tildes, axis=0)
        w_tilde_sum_norm = np.linalg.norm(w_tilde_sum)
        w_2_direction = w_tilde_sum / w_tilde_sum_norm if w_tilde_sum_norm > 0 else w_tilde_sum

        # project each trajectory onto (w_1_direction, w_2_direction)
        projected_trajectories = []
        for trajectory in trajectories:
            W = np.array(trajectory)  # shape (t_steps+1, d)
            proj_1 = W @ w_1_direction
            proj_2 = W @ w_2_direction
            projected_trajectories.append(np.stack([proj_1, proj_2], axis=1))

        if plot:
            plt.figure(figsize=(7, 7))
            for idx, proj in enumerate(projected_trajectories):
                plt.plot(proj[:, 0], proj[:, 1], marker="o", markersize=2,
                         label=f"trajectory {idx}")
                plt.scatter(proj[0, 0], proj[0, 1], color="black", zorder=5)  # start
                plt.scatter(proj[-1, 0], proj[-1, 1], color="red", zorder=5)  # end
            plt.xlabel("w_1 = w* direction")
            plt.ylabel("w_2 = sum(w_tilde) direction")
            plt.title("GD trajectories projected onto (w*, sum w_tilde) plane")
            plt.legend()
            plt.tight_layout()
            plt.show()

        return {
            "trajectories": trajectories,
            "w_tildes": w_tildes,
            "w_1_direction": w_1_direction,
            "w_2_direction": w_2_direction,
            "projected_trajectories": projected_trajectories,
        }
        # ------------------------------------------
    def LLM_generated_region_experiment_v2(self, number_of_trajectories, w_star,
                                            d=None, n=None, t_steps=1000, eta=None,
                                            Sigma=None, lambda_diag=None, use_lambda_diag=True,
                                            normalize_w_tilde=False, plot=True, 
                                            test_sample_size = int(3e3),
                                            measure_population_loss_for_iterates = True,
                                            ):
        # Similar to V1 version of the function, except that, 
        # we are also generating test samples (if measure_population_loss_for_iterates = True). 
        # For each trajectory, we want to keep track of the early stopping point and argmin of test loss (population loss)

        # LLM GENERATED PART ----------------------
        # Extends V1: besides collecting GD trajectories + max-margin w_tilde and
        # projecting onto (w_star, sum w_tilde), we also (optionally) approximate
        # the *population* loss with a single held-out test set of size
        # `test_sample_size`, and per trajectory we record two stopping points:
        #   - test_loss_argmin_index: argmin_t of the (population) test logistic loss
        #                             -> the "best" iterate to stop at.
        #   - early_stop_index:       first t with training loss <= L_hat(w*_{0:k})
        #                             -> the oracular early-stopping rule used in
        #                                plot_loss_over_time.
        # Indices are into w_trajectory (loss[t] corresponds to w_trajectory[t]).
        # ------------------------------------------
        if d is None:
            d = self.d
        if n is None:
            n = self.n
        if eta is None:
            eta = self.eta

        # single shared test set approximating the population (same data distribution
        # for every trajectory, so one test set suffices).
        X_test = y_test = None
        if measure_population_loss_for_iterates:
            X_test, y_test = self.generate_data(
                d, int(test_sample_size), w_star, Sigma=Sigma,
                lambda_diag=lambda_diag, use_lambda_diag=use_lambda_diag
            )

        trajectories = []
        w_tildes = []
        early_stop_t = []        # per trajectory: t of oracular early stop
        test_loss_argmin_t = []  # per trajectory: t of argmin population (test) loss

        for i in range(number_of_trajectories):
            X_data, y_data = self.generate_data(
                d, n, w_star, Sigma=Sigma, lambda_diag=lambda_diag,
                use_lambda_diag=use_lambda_diag
            )

            result = self.run_GD_for_t_steps(
                X_data, y_data, eta=eta, t_steps=t_steps,
                X_test=X_test, y_test=y_test,
                store_w_trajectory=True,
                store_log_loss_traj_for_training=True,
                store_log_loss_traj_for_test=measure_population_loss_for_iterates,
            )
            trajectory = result["w_trajectory"]

            w_tilde = self.find_w_tilde(X_data, y_data, normalize=normalize_w_tilde)

            trajectories.append(trajectory)
            w_tildes.append(w_tilde)

            test_log_loss = result["log_loss_test"]

            # oracular early-stopping point: first t with L_hat(w_t) <= L_hat(w*_{0:k}),
            # measured on HELD-OUT (test) data so it reflects population, not training,
            # behavior. Both the threshold L_hat(w*) and the loss trajectory use X_test.
            es_t = None
            if measure_population_loss_for_iterates and len(test_log_loss) > 0:
                L_hat_w_star = self.oracular_ell_hat_w_star_zero_to_k(X_test, y_test, w_star)
                for t, loss in enumerate(test_log_loss):
                    if loss <= L_hat_w_star:
                        es_t = t
                        break
            early_stop_t.append(es_t)

            # argmin of the population (test) logistic loss
            am_t = None
            if measure_population_loss_for_iterates and len(test_log_loss) > 0:
                am_t = int(np.argmin(test_log_loss))
            test_loss_argmin_t.append(am_t)

        # w_1 axis: direction of w_star
        w_star_norm = np.linalg.norm(w_star)
        w_1_direction = w_star / w_star_norm if w_star_norm > 0 else w_star

        # w_2 axis: direction of the sum of all w_tilde[i]
        w_tilde_sum = np.sum(w_tildes, axis=0)
        w_tilde_sum_norm = np.linalg.norm(w_tilde_sum)
        w_2_direction = w_tilde_sum / w_tilde_sum_norm if w_tilde_sum_norm > 0 else w_tilde_sum

        # project each trajectory onto (w_1_direction, w_2_direction)
        projected_trajectories = []
        for trajectory in trajectories:
            W = np.array(trajectory)  # shape (t_steps+1, d)
            proj_1 = W @ w_1_direction
            proj_2 = W @ w_2_direction
            projected_trajectories.append(np.stack([proj_1, proj_2], axis=1))

        if plot:
            plt.figure(figsize=(7, 7))
            for idx, proj in enumerate(projected_trajectories):
                plt.plot(proj[:, 0], proj[:, 1], marker="o", markersize=2,
                         label=f"trajectory {idx}")
                plt.scatter(proj[0, 0], proj[0, 1], color="black", zorder=5)  # start
                plt.scatter(proj[-1, 0], proj[-1, 1], color="red", zorder=5)  # end
                # mark the two stopping points along the trajectory
                es = early_stop_t[idx]
                am = test_loss_argmin_t[idx]
                if es is not None:
                    plt.scatter(proj[es, 0], proj[es, 1], color="green",
                                marker="s", zorder=6,
                                label="early stop" if idx == 0 else None)
                if am is not None:
                    plt.scatter(proj[am, 0], proj[am, 1], color="purple",
                                marker="*", s=120, zorder=6,
                                label="test-loss argmin" if idx == 0 else None)
            plt.xlabel("w_1 = w* direction")
            plt.ylabel("w_2 = sum(w_tilde) direction")
            plt.title("GD trajectories projected onto (w*, sum w_tilde) plane")
            plt.legend()
            plt.tight_layout()
            plt.show()

        return {
            "trajectories": trajectories,
            "w_tildes": w_tildes,
            "w_1_direction": w_1_direction,
            "w_2_direction": w_2_direction,
            "projected_trajectories": projected_trajectories,
            "early_stop_t": early_stop_t,
            "test_loss_argmin_t": test_loss_argmin_t,
        }
        # ------------------------------------------

